### PR TITLE
add link to pieces repo in header

### PR DESCRIPTION
**Pull request by gc**
unknown

### CODE REVIEW

**Comment by bdistin** [comment]
The order and/or inclusion is questionable.

**Comment by gc** [comment]
In the header I feel it gives it more attention, often a lot of new people don't know klasa-pieces repo exists, and a huge amount of free pieces that you can paste into your bot is definitely a big upside of klasa thats good to show off, not exactly something other frameworks can boast.

as for the order, I didn't really think about the order, can obviously be re-ordered easily - not sure what you mean by inclusion, but if you dont feel the header is the right place for it thats cool, maybe another place it can be displayed? (homepage/ footer/docs)

**Comment by bdistin** [comment]
Yes, inclusion is directly meaning in the header. Other places may be more suitable, and it surely deserves inclusion somewhere. Just probably not in the header.

And yes the order is easy to change, it's a matter of deciding where it would fit best. Right now, the order mirrors the mindset someone should have when working with klasa and not knowing something. Check the docs first, ask in the discord, and if all that has failed finally make an issue/pr to address whatever it is. Pieces doesn't really fit anywhere in that subliminal order.

**Comment by gc** [comment]
Makes sense. A card/tile on the homepage below the current 4 seems most appropriate after looking at the alternate places? could be integrated into the existing "About Us" tile to save space if thats preferable

A mention in the docs could be done in a pretty useful way perhaps - in the "Creating Commands" (and the others) section, it could have something like this: "For some examples on some command pieces, check out https://github.com/dirigeants/klasa-pieces/tree/master/commands" - as we often do refer newbies to them anyway for learning purposes

**Pull request closed without merging**
