### PR TITLE
chore: take a 🧹 through this repo

### PR DESCRIPTION
**Pull request by Favna**
- Removed discord links from the navbar
- Updated README status badge to reference github actions
- Changed deprecation message to be less passive aggressive

<details> <summary> New page dark mode </summary>

image

</details>

<details> <summary> New page light mode </summary>

image

</details>

### CODE REVIEW

**Comment by cfanoulis** [comment]
The docs one should not be removed. Klasa 0.5 exists and will continue to exist until v13 releases

**Review by cfanoulis — CHANGES_REQUESTED** [review]
^

**Comment by tjrgg** [comment]
I don't agree with the docs being removed. Why is that even being considered?

**Comment by tjrgg** [comment]
Also, the note is a bit much. A simple message that klasa isn't being currently maintained is all that's necessary.

**Comment by Favna** [comment]
Give me a moment to do some restoration....

**Review by cfanoulis — APPROVED** [review]
thank you favna very cool

**Pull request merged**
